[tool.flask-livetw]
flask_root = "."
static_folder = "static"
templates_folder = "templates"
templates_glob = "**/*.html"
base_layout = "layout.html"
livetw_folder = ".dev"
flask_app = "notion_model.py"
