name: Update Total Nuevas

on:
  schedule:
    - cron: '15 13 * * 1'   # Runs every Monday at 10:15
  push:
    branches:
      - mitades  # Replace 'main' with your branch name if different

jobs:
  update-total-nuevas:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Update Total Nuevas
        run: |
          curl -X GET "https://oportunidades.lat/update_total_nuevas"
